# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-26 03:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 25, 22, 49, 8, 475737), null=True)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('archivo', models.CharField(blank=True, max_length=1000, null=True)),
                ('texto', models.CharField(blank=True, max_length=1000, null=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Ocupacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(blank=True, max_length=1000, null=True)),
                ('lng', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Position',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1000, null=True)),
                ('edad', models.CharField(blank=True, max_length=1000, null=True)),
                ('lat', models.CharField(blank=True, max_length=1000, null=True)),
                ('lng', models.CharField(blank=True, max_length=1000, null=True)),
                ('iconData', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('icon', models.CharField(blank=True, max_length=1000, null=True)),
                ('ocupacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='choose.Ocupacion')),
            ],
            options={
                'verbose_name': 'Usuarios',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='position',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='choose.Usuarios'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='choose.Usuarios'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='choose.Usuarios'),
        ),
    ]
