# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-26 03:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0002_auto_20190625_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 25, 22, 50, 55, 271539), null=True),
        ),
    ]
