# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-03 17:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0002_auto_20190603_1241'),
    ]

    operations = [

    ]
