# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-26 04:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0003_auto_20190625_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocupacion',
            name='icon',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 25, 23, 22, 15, 193376), null=True),
        ),
    ]
