# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-03 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0004_auto_20190603_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrosturistico',
            name='caption',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
    ]
