# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-27 03:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0004_auto_20190625_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='foto',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 26, 22, 42, 28, 442944), null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='ocupacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='choose.Ocupacion'),
        ),
    ]
