# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-06 16:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0006_auto_20190701_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 6, 11, 32, 48, 25339), null=True),
        ),
    ]
