# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-13 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0007_auto_20190613_1628'),
    ]

    operations = [
       
    ]
