# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-13 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0008_paymentsub_hotel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'managed': True},
        )
    ]
