# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-11 02:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0008_auto_20190710_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 10, 21, 53, 28, 740763), null=True),
        ),
    ]
