# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-11 03:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0009_auto_20190710_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='descripcion',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 10, 22, 10, 20, 73065), null=True),
        ),
    ]
