# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-12 02:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0010_auto_20190710_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formapago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Forma Pago',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 11, 21, 9, 43, 217571), null=True),
        ),
    ]
