# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-13 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0010_auto_20190613_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentsub',
            options={'managed': False},
        ),
    ]
