# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-12 02:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0012_auto_20190711_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='precio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 11, 21, 17, 47, 837134), null=True),
        ),
    ]
