# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-13 14:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0014_auto_20190711_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 13, 9, 1, 1, 889957), null=True),
        ),
    ]
