# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-19 03:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0018_auto_20190718_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 18, 22, 23, 21, 956791), null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 18, 22, 23, 21, 958593), null=True),
        ),
    ]
