# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-21 14:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0020_auto_20190721_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='estrella',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 21, 9, 25, 51, 806895), null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 21, 9, 25, 51, 805252), null=True),
        ),
    ]
