# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-26 23:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0021_auto_20190721_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intercambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 26, 18, 10, 28, 215244), null=True)),
                ('deseo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deseo', to='choose.Ocupacion')),
                ('ofrezco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofrezco', to='choose.Ocupacion')),
            ],
            options={
                'verbose_name': 'Intercambio',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 26, 18, 10, 28, 214131), null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 26, 18, 10, 28, 212508), null=True),
        ),
    ]
