# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-26 23:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0024_auto_20190726_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambio',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interuser', to='choose.Usuarios'),
        ),
        migrations.AlterField(
            model_name='intercambio',
            name='deseo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interdeseo', to='choose.Ocupacion'),
        ),
        migrations.AlterField(
            model_name='intercambio',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 26, 18, 42, 2, 894732), null=True),
        ),
        migrations.AlterField(
            model_name='intercambio',
            name='ofrezco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interofrezco', to='choose.Ocupacion'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 26, 18, 42, 2, 893719), null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 26, 18, 42, 2, 891998), null=True),
        ),
    ]
