# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-30 16:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0026_auto_20190727_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocupacion',
            options={'managed': True, 'verbose_name': 'Servicios y Productos'},
        ),
        migrations.AddField(
            model_name='ocupacion',
            name='categoria',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='intercambio',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 30, 11, 38, 6, 780821), null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 30, 11, 38, 6, 779701), null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 30, 11, 38, 6, 777996), null=True),
        ),
    ]
