# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-08-01 04:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0036_auto_20190731_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='publicidadcompartir',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='intercambio',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 31, 23, 44, 34, 197297), null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 31, 23, 44, 34, 196173), null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 31, 23, 44, 34, 194489), null=True),
        ),
    ]
