# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-08-02 21:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0037_auto_20190731_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='eliminado',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='intercambio',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 2, 16, 25, 10, 935665), null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 2, 16, 25, 10, 934420), null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 2, 16, 25, 10, 932741), null=True),
        ),
    ]
