# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-08-03 03:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0039_auto_20190802_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambio',
            name='eliminado',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='intercambio',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 2, 22, 33, 15, 55059), null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 2, 22, 33, 15, 53888), null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 2, 22, 33, 15, 52103), null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='publicidadcompartir',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
